### ISSUE TITLE
What are the CONCEPTNET_TRAIN_CORPUS?

### ISSUE THREAD

**Issue by li3cmz** [allenai/commonsense-kg-completion#1]
Hello, 
     could you tell me more details about the CONCEPTNET_TRAIN_CORPUS for lm_finetuning?

**Comment by tsafavi** [comment]
Hi @chaitanyamalaviya, I have the same question. Thanks!

**Comment by chaitanyamalaviya** [comment]
Hi! This variable is the path to the node names in the preprocessed ConceptNet training corpus linked in the readme (https://drive.google.com/file/d/1R4C2s8QWwdNE9CUwtfhsYevmM7V-01YT/view) or found [here](https://ttic.uchicago.edu/~kgimpel/commonsense.html).

**Comment by tsafavi** [comment]
I see, so when you say "train corpus", in this case it just means a set of KB triples?

**Comment by chaitanyamalaviya** [comment]
For the purpose of lm finetuning, the training corpus is actually the set of unique natural language phrases represented by the nodes in the graph (and not KB triples).

**Comment by tsafavi** [comment]
Hm, still not clear to me - say you have a set of ```<head node phrase> <relation> <tail node phrase>``` KB triples. If I understand correctly, the corpus is just the (unique) head/tail node phrases, and the relations are excluded? I think I'm confused because many of the node names in ConceptNet are not phrases but single tokens - do you consider the single token node names as "phrases" for fine tuning as well?

**Comment by chaitanyamalaviya** [comment]
That's right, the corpus is just the (unique) head/tail node phrases, and relations are excluded. And yes, the single token node names were also treated as phrases for finetuning.

**Comment by tsafavi** [comment]
👍 thanks for your help!
